// Code generated by "stringer -type=CompareType -output=compare_type_string.go"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompareTypeEqual-1]
	_ = x[CompareTypeNotEqual-2]
	_ = x[CompareTypeContain-3]
	_ = x[CompareTypeNotContain-4]
	_ = x[CompareTypeRegexp-5]
	_ = x[CompareTypeGreatThan-6]
	_ = x[CompareTypeLessThan-7]
	_ = x[CompareTypeBoolean-8]
}

const _CompareType_name = "CompareTypeEqualCompareTypeNotEqualCompareTypeContainCompareTypeNotContainCompareTypeRegexpCompareTypeGreatThanCompareTypeLessThanCompareTypeBoolean"

var _CompareType_index = [...]uint8{0, 16, 35, 53, 74, 91, 111, 130, 148}

func (i CompareType) String() string {
	i -= 1
	if i < 0 || i >= CompareType(len(_CompareType_index)-1) {
		return "CompareType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CompareType_name[_CompareType_index[i]:_CompareType_index[i+1]]
}
